name: Swift

env:
  PROJECT: GithubActionsWithSwift
  XCODE_PROJECT: GithubActionsWithSwift.xcodeproj
  SIMULATOR: iPhone 11 Pro Max
  XCODE: Xcode_11.5

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Force Xcode 11.5
        run: sudo xcode-select -switch '/Applications/${env.XCODE}.app'

      - name: Build
        run: xcodebuild -project env.XCODE_PROJECT -scheme env.PROJECT -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

      - name: Run tests
        run: xcodebuild clean test -project $XCODE_PROJECT -scheme $PROJECT -destination 'platform=iOS Simulator,name=${env.SIMULATOR},OS=latest'
