name: Swift

env:
  PROJECT: GithubActionsWithSwift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo $PROJECT".xcodeproj"
        # run: xcodebuild -project $PROJECT".xcodeproj" -scheme $PROJECT -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
      # - name: Run tests
      # run: xcodebuild clean test -project $PROJECT".xcodeproj" -scheme $PROJECT -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
